# Generated by Django 4.1.7 on 2023-03-07 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(default='+21600000000', max_length=20)),
                ('birthdate', models.DateField(default=datetime.date(1995, 11, 11))),
                ('typeClient', models.CharField(choices=[('LOYAL', 'Loyal Customer'), ('NorMAL', 'Normal Customer'), ('VIP', ' Vip Customer')], default='Normal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=20)),
                ('price', models.FloatField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/product_image')),
                ('description', models.TextField(blank=True, null=True)),
                ('expirationDate', models.DateField(default=datetime.date(2023, 12, 31))),
                ('fabricationDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 3, 7, 10, 36, 39, 598342, tzinfo=datetime.timezone.utc))),
                ('quality', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='clientProduct',
            field=models.ManyToManyField(through='e_commerceApp.Command', to='e_commerceApp.product'),
        ),
    ]
