# Generated by Django 4.1.7 on 2023-05-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerceApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history',
        ),
    ]
