# Generated by Django 4.1.7 on 2023-05-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerceApp', '0002_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='typeClient',
            field=models.CharField(choices=[('LOYAL', 'Loyal Customer'), ('Normall', 'Normal Customer'), ('VIP', ' Vip Customer')], default='Normal', max_length=50),
        ),
    ]
